#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

ABBREV='<ABBREV>'
STR_RUBY_VERSIONS=''
STR_BUNDLER_VERSIONS=''
STR_RAILS_VERSIONS=''
STR_PG_VERSIONS=''
STR_NOKOGIRI_VERSIONS=''
STR_FFI_VERSIONS=''

source ~/.rvm/scripts/rvm # Activate RVM

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use node # Activate Node

echo '##########################'
echo "BEGIN $ABBREV-user actions"
echo '##########################'

echo '----------------------------------------------------------------------------------------------'
echo 'wget https://gitlab.com/rubyonracetracks/docker-common/raw/main/rvm-install-rubies.sh'
wget https://gitlab.com/rubyonracetracks/docker-common/raw/main/rvm-install-rubies.sh

echo '------------------------------'
echo 'Updating rvm-install-rubies.sh'
sed -i.bak "s|<STR_RUBY_VERSIONS>|$STR_RUBY_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_BUNDLER_VERSIONS>|$STR_BUNDLER_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_RAILS_VERSIONS>|$STR_RAILS_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_PG_VERSIONS>|$STR_PG_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_NOKOGIRI_VERSIONS>|$STR_NOKOGIRI_VERSIONS|g" rvm-install-rubies.sh
sed -i.bak "s|<STR_FFI_VERSIONS>|$STR_FFI_VERSIONS|g" rvm-install-rubies.sh
rm rvm-install-rubies.sh.bak

echo '---------------------------------------------------------------'
echo 'sudo mv rvm-install-rubies.sh /usr/local/bin/rvm-install-rubies'
sudo mv rvm-install-rubies.sh /usr/local/bin/rvm-install-rubies

echo '-----------------------------------------------'
echo 'sudo chmod +x /usr/local/bin/rvm-install-rubies'
sudo chmod +x /usr/local/bin/rvm-install-rubies

/usr/local/bin/rvm-install-rubies

echo '#############################'
echo "FINISHED $ABBREV-user actions"
echo '#############################'
