#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

ABBREV='<ABBREV>'
REGULAR_USER='<REGULAR_USER>'

T_BEGIN=$(date +'%s')

echo '--------------------'
echo 'ls -l /usr/local/bin'
ls -l /usr/local/bin

# Prepare apt-get
/usr/local/bin/aptget

# Set environment variables to cut down on annoying warning messages
export DEBIAN_FRONTEND='noninteractive'
export DEBCONF_NOWARNINGS='true'
export HOME=/root
export LC_ALL=C

echo '##########################'
echo "BEGIN $ABBREV-root actions"
echo '##########################'

echo "/usr/local/bin/check-$ABBREV" >> /usr/local/bin/check

echo 'Nothing to do as root'

echo '#############################'
echo "FINISHED $ABBREV-root actions"
echo '#############################'

su -c /usr/local/bin/$ABBREV-user $REGULAR_USER
/usr/local/bin/finalize-root
su -c /usr/local/bin/finalize-user $REGULAR_USER
su -c /usr/local/bin/check $REGULAR_USER

T_FINISH=$(date +'%s')
T_ELAPSED=$(($T_FINISH-$T_BEGIN))
echo '--------------------------------'
echo 'Time to modify the Docker image:'
echo "$(($T_ELAPSED / 60)) minutes and $(($T_ELAPSED % 60)) seconds"
