#!/bin/bash

# NOTE: set -o pipefail is needed to ensure that any error or failure causes the whole pipeline to fail.
# Without this specification, the CI status will provide a false sense of security by showing builds
# as succeeding in spite of errors or failures.
set -eo pipefail

ABBREV='<ABBREV>'

# BEGIN: activate NVM
export NVM_DIR="/home/`whoami`/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh"
# END: activate NVM

nvm use node # Activate Node

source ~/.rvm/scripts/rvm # Activate RVM

echo '###########################'
echo "BEGIN $ABBREV sanity checks"
echo '###########################'

echo '--------'
echo 'rvm list'
rvm list

echo '-------'
echo 'ruby -v'
ruby -v

echo '--------'
echo 'rails -v'
rails -v

echo '------------------'
echo 'gem list "^rails$"'
gem list "^rails$"

echo '-----------------'
echo 'bundler --version'
bundler --version

echo '--------------------'
echo 'gem list "^bundler$"'
gem list "^bundler$"

echo '---------------------'
echo 'gem list "^nokogiri$"'
gem list "^nokogiri$"

echo '---------------'
echo 'gem list "^pg$"'
gem list "^pg$"

echo '----------------'
echo 'gem list "^ffi$"'
gem list "^ffi$"

echo '------------------------'
echo 'gem list "^mailcatcher$"'
gem list "^mailcatcher$"

echo '##############################'
echo "FINISHED $ABBREV sanity checks"
echo '##############################'
